# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coord_correc_func_cpp <- function(theta, coordinate_correction) {
    .Call('_priorSens_coord_correc_func_cpp', PACKAGE = 'priorSens', theta, coordinate_correction)
}

